name: Flutter Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Menambahkan environment variable agar pakai Node terbaru sesuai saran GitHub
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.2'
          channel: 'stable'

      - name: Get Dependencies
        run: flutter pub get

      # INI MANTRA BARUNYA: Memaksa Flutter membuat ulang file Android yang hilang
      - name: Generate Missing Android Files
        run: flutter create . --platforms=android

      # Sekarang file gradlew pasti sudah ada, baru kita beri izin
      - name: Make Gradlew Executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: flutter build apk --release --split-per-abi --android-skip-build-dependency-validation

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/*.apk